In [63]:
import tensorflow as tf
import  numpy as np
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer
cv =CountVectorizer()
from sklearn import preprocessing
le = preprocessing.LabelEncoder()
from sklearn.naive_bayes import MultinomialNB
model=MultinomialNB()

In [64]:
f=pd.read_csv("chat.csv")

In [65]:
f

inputs    classes
0                     who are you  assistant
1                 who created you  assistant
2               describe yourself  assistant
3                your information  assistant
4   please tell me about yourself  assistant
5             why was you created  assistant
6                what is your age  assistant
7         tell something about me     family
8      tell  information about me     family
9                        who I am     family
10      tell members in my family     family
11                 family members     family
12       how many brothers I have     family
13               who is my father    family1
14                         father    family1
15                         mother    family1
16               who is my mother    family1
17                    how are you    feeling
18           what are you feeling    feeling
19                   festive mode    feeling
20                         exited    feeling
21                 are you exited    feeling
22       what is the festival now    feeling
23                ganesh chaturti    feeling
24                             hi   greeting
25                    How are you   greeting
26                Is anyone there   greeting
27                          Hello   greeting
28                       Good day   greeting
29                       whats up   greeting
30                  See you later       over
31                        goodbye       over
32                   I am Leaving       over
33                Have a Good day       over

In [66]:
x=f.drop(["classes"],axis=1)
y=f.drop(["inputs"],axis=1)

In [67]:
x

inputs
0                     who are you
1                 who created you
2               describe yourself
3                your information
4   please tell me about yourself
5             why was you created
6                what is your age
7         tell something about me
8      tell  information about me
9                        who I am
10      tell members in my family
11                 family members
12       how many brothers I have
13               who is my father
14                         father
15                         mother
16               who is my mother
17                    how are you
18           what are you feeling
19                   festive mode
20                         exited
21                 are you exited
22       what is the festival now
23                ganesh chaturti
24                             hi
25                    How are you
26                Is anyone there
27                          Hello
28                       Good day
29                       whats up
30                  See you later
31                        goodbye
32                   I am Leaving
33                Have a Good day

In [68]:
x=x.inputs.str.lower()
x

0                       who are you
1                   who created you
2                 describe yourself
3                  your information
4     please tell me about yourself
5               why was you created
6                  what is your age
7           tell something about me
8        tell  information about me
9                          who i am
10        tell members in my family
11                   family members
12         how many brothers i have
13                 who is my father
14                           father
15                           mother
16                 who is my mother
17                      how are you
18             what are you feeling
19                     festive mode
20                           exited
21                   are you exited
22         what is the festival now
23                  ganesh chaturti
24                               hi
25                      how are you
26                  is anyone there
27                          

In [69]:
x.head(10)

0                      who are you
1                  who created you
2                describe yourself
3                 your information
4    please tell me about yourself
5              why was you created
6                 what is your age
7          tell something about me
8       tell  information about me
9                         who i am
Name: inputs, dtype: object

In [70]:
y.head(10
      )

classes
0  assistant
1  assistant
2  assistant
3  assistant
4  assistant
5  assistant
6  assistant
7     family
8     family
9     family

In [71]:
x=cv.fit_transform(x).toarray()
x

array([[0, 0, 0, ..., 1, 0, 0],
       [0, 0, 0, ..., 1, 0, 0],
       [0, 0, 0, ..., 0, 0, 1],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 1, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [72]:
y=le.fit_transform(y)
y

/home/sai/anaconda3/envs/tensor/lib/python3.9/site-packages/sklearn/preprocessing/_label.py:115: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


array([0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3, 3,
       3, 3, 4, 4, 4, 4, 4, 4, 5, 5, 5, 5])

In [74]:
model=model.fit(x,y)

In [78]:
t=["happy ganesh chatuti to you /home/sai/anaconda3/envs/tensor/lib/python3.9/site-packages/sklearn/preprocessing/_label.py:115: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)"]

t=cv.fit_transform(t).toarray()
t

array([[1, 1, 1, 1, 1]])

In [79]:
m2=model.predict(t)
m2

ValueError: X has 5 features, but MultinomialNB is expecting 50 features as input.